export const CARD_BRANDS: Record<string, any> = {
  'nubank':                             require('../assets/cards/nubank.png'),
  'nubank-ultravioleta':                require('../assets/cards/nubank-ultravioleta.png'),
  'nubanck-black':                      require('../assets/cards/nubanck-black.png'),
  'inter':                              require('../assets/cards/inter.png'),
  'inter-prime':                        require('../assets/cards/inter-prime.png'),
  'itau-azul-visa':                     require('../assets/cards/itau-azul-visa.png'),
  'itau-the-one':                       require('../assets/cards/itau-the-one.png'),
  'itau-platium':                       require('../assets/cards/itau-platium.png'),
  'itau-personalite-black':             require('../assets/cards/itau-personalite-black.png'),
  'itau-latam-pass':                    require('../assets/cards/itau-latam-pass.png'),
  'itau-personnalite-visa-infinite':    require('../assets/cards/itau-personnalite-visa-infinite.png'),
  'bradesco-elo-mais':                  require('../assets/cards/bradesco-elo-mais.png'),
  'bradesco-elo-nanquim-card':          require('../assets/cards/bradesco-elo-nanquim-card.png'),
  'bradesco-visa-infinite':             require('../assets/cards/bradesco-visa-infinite.png'),
  'bradesco-visa-neo':                  require('../assets/cards/bradesco-visa-neo.png'),
  'bradesco-visa-platinum-internacional': require('../assets/cards/bradesco-visa-platinum-internacional.png'),
  'cartao-bradesco-like-visa':          require('../assets/cards/cartao-bradesco-Like-visa.png'),
  'cartao-disney-visa':                 require('../assets/cards/cartao-disney-visa.png'),
  'santander-free':                     require('../assets/cards/santander-free.png'),
  'santander-sx':                       require('../assets/cards/santander-sx.png'),
  'santander-aa':                       require('../assets/cards/santander-aa.png'),
  'santander-advantage':                require('../assets/cards/santander-advantage.png'),
  'santander-unique':                   require('../assets/cards/santander-unique.png'),
  'cartao-santander-free':              require('../assets/cards/cartao-santander-free.png'),
  'amex-gold':                          require('../assets/cards/amex-gold.png'),
  'amex-green':                         require('../assets/cards/amex-green.png'),
  'amex-platium':                       require('../assets/cards/amex-platium.png'),
  'bb-altus':                           require('../assets/cards/bb-altus.png'),
  'brb-fla':                            require('../assets/cards/brb-fla.png'),
  'brb-fla-black':                      require('../assets/cards/brb-fla-black.png'),
  'brb-mastercard-black':               require('../assets/cards/brb-mastercard-black.png'),
  'brb-visa-gold':                      require('../assets/cards/brb-visa-gold.png'),
  'brb-visa-platium':                   require('../assets/cards/brb-visa-platium.png'),
  'BRB-Visa-Platinum':                  require('../assets/cards/BRB-Visa-Platinum.png'),
  'BTG-Pactual-Black':                  require('../assets/cards/BTG-Pactual-Black.png'),
  'c6-mastercard-platinum':             require('../assets/cards/c6-mastercard-platinum.png'),
  'carbon-c6-black':                    require('../assets/cards/carbon-c6-black.png'),
  'nanquim-elo-contactless':            require('../assets/cards/nanquim_elo_contactless.png'),
  'grafite-elo-contactless':            require('../assets/cards/grafite_elo_contactless.png'),
  'sim-elo-contactless':                require('../assets/cards/sim_elo_contactless.png'),
  'dux-brb':                            require('../assets/cards/dux-brb.png'),
  'ourocard-elo':                       require('../assets/cards/ourocard-elo.png'),
  'ourocard-infinite':                  require('../assets/cards/ourocard-infinite.png'),
  'ourocard-platium':                   require('../assets/cards/ourocard-platium.png'),
  'latam-pass-black':                   require('../assets/cards/latam-pass-black.png'),
  'prime-visa-signature':               require('../assets/cards/prime-visa-signature.png'),
  'smiles-gold':                        require('../assets/cards/SMILES_GOLD_VS.png'),
  'smiles-infinite':                    require('../assets/cards/SMILES_INFINITE_VS.png'),
  'visa-bb-infinite':                   require('../assets/cards/Visa-BB-Infinite.png'),
  'caixa-visa-infinite':                require('../assets/cards/caixa-visa-infinite.png'),
  'visa-caixa-tem':                     require('../assets/cards/visa-caixa-tem.png'),
  'generic':                            require('../assets/cards/generic.png'),
}

export const CARD_BRAND_LABELS: Record<string, string> = {
  'nubank':                             'Nubank',
  'nubank-ultravioleta':                'Nubank Ultravioleta',
  'nubanck-black':                      'Nubank Black',
  'inter':                              'Inter',
  'inter-prime':                        'Inter Prime',
  'itau-azul-visa':                     'Itaú Azul Visa',
  'itau-the-one':                       'Itaú The One',
  'itau-platium':                       'Itaú Platinum',
  'itau-personalite-black':             'Itaú Personnalité Black',
  'itau-latam-pass':                    'Itaú LATAM Pass',
  'itau-personnalite-visa-infinite':    'Itaú Personnalité Visa Infinite',
  'bradesco-elo-mais':                  'Bradesco Elo Mais',
  'bradesco-elo-nanquim-card':          'Bradesco Elo Nanquim',
  'bradesco-visa-infinite':             'Bradesco Visa Infinite',
  'bradesco-visa-neo':                  'Bradesco Visa Neo',
  'bradesco-visa-platinum-internacional': 'Bradesco Visa Platinum',
  'cartao-bradesco-like-visa':          'Bradesco Like Visa',
  'cartao-disney-visa':                 'Disney Visa',
  'santander-free':                     'Santander Free',
  'santander-sx':                       'Santander SX',
  'santander-aa':                       'Santander AA',
  'santander-advantage':                'Santander Advantage',
  'santander-unique':                   'Santander Unique',
  'cartao-santander-free':              'Santander Free',
  'amex-gold':                          'Amex Gold',
  'amex-green':                         'Amex Green',
  'amex-platium':                       'Amex Platinum',
  'bb-altus':                           'BB Altus',
  'brb-fla':                            'BRB Fla',
  'brb-fla-black':                      'BRB Fla Black',
  'brb-mastercard-black':               'BRB Mastercard Black',
  'brb-visa-gold':                      'BRB Visa Gold',
  'brb-visa-platium':                   'BRB Visa Platinum',
  'BRB-Visa-Platinum':                  'BRB Visa Platinum',
  'BTG-Pactual-Black':                  'BTG Pactual Black',
  'c6-mastercard-platinum':             'C6 Mastercard Platinum',
  'carbon-c6-black':                    'C6 Carbon Black',
  'nanquim-elo-contactless':            'Nanquim Elo Contactless',
  'grafite-elo-contactless':            'Grafite Elo Contactless',
  'sim-elo-contactless':                'Sim Elo Contactless',
  'dux-brb':                            'DUX BRB',
  'ourocard-elo':                       'Ourocard Elo',
  'ourocard-infinite':                  'Ourocard Infinite',
  'ourocard-platium':                   'Ourocard Platinum',
  'latam-pass-black':                   'LATAM Pass Black',
  'prime-visa-signature':               'Prime Visa Signature',
  'smiles-gold':                        'Smiles Gold',
  'smiles-infinite':                    'Smiles Infinite',
  'visa-bb-infinite':                   'Visa BB Infinite',
  'caixa-visa-infinite':                'Caixa Visa Infinite',
  'visa-caixa-tem':                     'Caixa Tem',
  'generic':                            'Outro',
}

export const CARD_BRAND_LIST: string[] = [
  ...Object.keys(CARD_BRANDS)
    .filter(k => k !== 'generic')
    .sort((a, b) => (CARD_BRAND_LABELS[a] ?? a).localeCompare(CARD_BRAND_LABELS[b] ?? b, 'pt-BR')),
  'generic',
]

export function getCardImage(brand: string | null | undefined): any {
  if (!brand || !CARD_BRANDS[brand]) return CARD_BRANDS['generic']
  return CARD_BRANDS[brand]
}
